# Generated by Django 3.0.2 on 2020-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='classs',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example',
            name='types',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
